version: "2.4"

services:
  database:
    image: postgres:9.6.11-alpine
    restart: always
    ports:
    - 9999:5432
    environment:
      POSTGRES_PASSWORD: "${FP_DATABASE_PASS}"
      POSTGRES_USER: "${FP_DATABASE_USER}"
      POSTGRES_DB: "${FP_DATABASE_DBNAME}"
  noda:
    build: .
    depends_on:
    - database
    restart: always
    environment:
      DATABASE_URL: "${FP_DATABASE_URL}"
    ports:
    - 8889:3000