version: "2.4"

services:
  database:
    image: postgres:9.6.11-alpine
    restart: always
    ports:
    - 9999:5432
    environment:
      POSTGRES_USER: "${FP_DATABASE_USER}"
      POSTGRES_PASSWORD: "${FP_DATABASE_PASS}"
      POSTGRES_DB: "${FP_DATABASE_DBNAME}"
  noda:
    build: .
    depends_on:
    - database
    restart: always
    environment:
      DATABASE_URL: "${FP_DATABASE_URL}"
    ports:
    - 8889:3000
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2181:2181
  kafka:
    build: ./docker/kafka/
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "test-topic"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
