version: "2.4"

services:
  noda:
    build: .
    restart: always
    environment:
      DATABASE_URL: "postgres://root:111111@database:5432/testdb"
    ports:
    - 8889:3000


  database:
    image: postgres:9.6.11-alpine
    restart: always
    ports:
    - 9999:5432
    environment:
      POSTGRES_PASSWORD: "111111"
      POSTGRES_USER: "root"
      POSTGRES_DB: test_db
